# config/settings.py
import os
from dotenv import load_dotenv

# Load environment variables from a .env file
# Make sure you create a .env file in the project root with all required variables.
load_dotenv()

# --- General Settings ---
PROJECT_NAME = "AutonomousDigitalAlchemist"
NICHE_TOPIC = "Solar Pump Systems for Rajasthan Farmers"
# Target languages for content generation. Ensure LLMs support these.
# 'mr' (Marwari) is generally covered by 'hi' (Hindi) models or requires specific fine-tuning/data.
TARGET_LANGUAGES = ["en", "hi"]
CONTENT_VOLUME_PER_DAY = 20 # Target number of articles/guides per day initially

# --- API Keys & Credentials ---
# IMPORTANT: Replace these with your actual API keys in the .env file.
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY") # Optional fallback/alternative LLM
STABILITY_AI_API_KEY = os.getenv("STABILITY_AI_API_KEY") # For image generation
GCP_PROJECT_ID = os.getenv("GCP_PROJECT_ID") # Required for Google Cloud Text-to-Speech

# Scraping Service (e.g., Bright Data, ScraperAPI)
# Using Bright Data as an example. You'd need an account and API key.
BRIGHT_DATA_API_KEY = os.getenv("BRIGHT_DATA_API_KEY")
BRIGHT_DATA_ZONE = os.getenv("BRIGHT_DATA_ZONE", "residential") # e.g., residential, datacenter
BRIGHT_DATA_HOST = os.getenv("BRIGHT_DATA_HOST", "brd.superproxy.io")
BRIGHT_DATA_PORT = os.getenv("BRIGHT_DATA_PORT", "22225")

# CMS (WordPress)
WORDPRESS_API_URL = os.getenv("WORDPRESS_API_URL") # e.g., "https://yourdomain.com/wp-json"
WORDPRESS_USERNAME = os.getenv("WORDPRESS_USERNAME") # WordPress user with App Password capability
WORDPRESS_APP_PASSWORD = os.getenv("WORDPRESS_APP_PASSWORD") # Generated from WordPress user profile

# Social Media (Example - configure only what's needed and set up OAuth/API access)
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY") # For YouTube Data API v3 (uploading videos)
# TWITTER_BEARER_TOKEN = os.getenv("TWITTER_BEARER_TOKEN") # For Twitter API v2
# FACEBOOK_APP_ID = os.getenv("FACEBOOK_APP_ID")
# FACEBOOK_APP_SECRET = os.getenv("FACEBOOK_APP_SECRET")
# FACEBOOK_PAGE_ACCESS_TOKEN = os.getenv("FACEBOOK_PAGE_ACCESS_TOKEN")

# Database (PostgreSQL)
DB_HOST = os.getenv("DB_HOST", "db") # 'db' if using docker-compose, else your DB host
DB_PORT = os.getenv("DB_PORT", "5432")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_NAME = os.getenv("DB_NAME")
DATABASE_URL = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

# --- Content Generation Settings ---
MIN_ARTICLE_LENGTH_WORDS = 800
MAX_ARTICLE_LENGTH_WORDS = 2000
TEXT_GENERATION_MODEL = "gemini-pro" # Default LLM for text
IMAGE_GENERATION_MODEL = "stable-diffusion-v1-6" # Default model for Stability AI
VIDEO_GENERATION_SETTINGS = {
    "max_duration_seconds": 90,
    "voice_language_code": {"hi": "hi-IN", "en": "en-IN"},
    "voice_name": {"hi": "hi-IN-Wavenet-B", "en": "en-IN-Wavenet-D"} # Example voices, check GCP TTS docs
}

# --- SEO Settings ---
MIN_KEYWORDS_PER_ARTICLE = 5
MAX_KEYWORDS_PER_ARTICLE = 15

# --- Monetization Settings ---
ADSENSE_PUBLISHER_ID = os.getenv("ADSENSE_PUBLISHER_ID") # Your AdSense Publisher ID
ADSENSE_AD_SLOT_ID = os.getenv("ADSENSE_AD_SLOT_ID") # An example ad slot ID
AMAZON_ASSOCIATES_TAG = os.getenv("AMAZON_ASSOCIATES_TAG") # Your Amazon Associates Tag
# Razorpay (for selling digital products)
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")

# --- Agent Orchestration (Celery) ---
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0") # 'redis' if using docker-compose
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/0")

# --- Legal & Compliance ---
# MeitY Advisory (March 2024) requires labeling of AI-generated content.
AI_CONTENT_DISCLAIMER_TEXT = "यह सामग्री एक एआई प्रणाली द्वारा उत्पन्न की गई है। सटीकता के लिए प्रयास किए जाते हैं, कृपया महत्वपूर्ण जानकारी किसी विशेषज्ञ से सत्यापित करें। (This content was generated by an AI system. While efforts are made for accuracy, please verify critical information with an expert.)"
AI_CONTENT_DISCLAIMER_ENABLED = True

# --- Paths ---
DATA_DIR = "data"
